CREATE TABLE PUBLIC.USER
(
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  LOGIN VARCHAR(15) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(40) NOT NULL,
  FIRSTNAME VARCHAR(25) NOT NULL,
  SURNAME VARCHAR(25) NOT NULL,
  PATRONYMIC VARCHAR(25) NOT NULL,
  GENDER INT NOT NULL,
  ADDRESS VARCHAR(25) NOT NULL,
  MOBILE_PHONE VARCHAR(11) NOT NULL,
  ROLE INT NOT NULL,
  STATUS BOOLEAN
);
CREATE UNIQUE INDEX "USER_ID_uindex" ON PUBLIC.USER (ID);
CREATE UNIQUE INDEX "USER_LOGIN_uindex" ON PUBLIC.USER (LOGIN);
CREATE UNIQUE INDEX "USER_EMAIL_uindex" ON PUBLIC.USER (EMAIL);
CREATE UNIQUE INDEX "USER_MOBILE_PHONE_uindex" ON PUBLIC.USER (MOBILE_PHONE);

CREATE TABLE PUBLIC.ROLE
(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ROLE_TYPE VARCHAR(20) NOT NULL
);
CREATE UNIQUE INDEX "ROLE_id_uindex" ON PUBLIC.ROLE (id);
CREATE UNIQUE INDEX "ROLE_ROLE_TYPE_uindex" ON PUBLIC.ROLE (ROLE_TYPE);

INSERT INTO PUBLIC.ROLE(ID, ROLE_TYPE) VALUES
  (1, 'ADMIN'),
  (2, 'USER');

CREATE TABLE PUBLIC.GENDER
(
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  GENDER_TYPE VARCHAR(15) NOT NULL
);
CREATE UNIQUE INDEX "GENDER_ID_uindex" ON PUBLIC.GENDER (ID);
CREATE UNIQUE INDEX "GENDER_GENDER_TYPE_uindex" ON PUBLIC.GENDER (GENDER_TYPE);

INSERT INTO PUBLIC.GENDER(ID, GENDER_TYPE) VALUES
  (1, 'MALE'),
  (2, 'FEMALE');